function y = LPF_fs40MHz_20Mpass_21Mstop(x)
%LPF_FS40MHZ_20MPASS_21MSTOP Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
% Generated on: 15-Feb-2015 21:59:16

persistent Hd;

if isempty(Hd)
    
    Fpass = 10000000;  % Passband Frequency
    Fstop = 11000000;  % Stopband Frequency
    Apass = 1;         % Passband Ripple (dB)
    Astop = 80;        % Stopband Attenuation (dB)
    Fs    = 40000000;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


